//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomRoslyn.Analyzer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomRoslyn.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class Controller or one more public methods haven&apos;t  Authorize attribute.
        /// </summary>
        internal static string AuthorizeAttributeAnalyzerDescription {
            get {
                return ResourceManager.GetString("AuthorizeAttributeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class &apos;{0}&apos; or one more public methods haven&apos;t  Authorize attribute.
        /// </summary>
        internal static string AuthorizeAttributeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AuthorizeAttributeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class Controller or all public methods shoud have  Authorize attribute.
        /// </summary>
        internal static string AuthorizeAttributeAnalyzerTitle {
            get {
                return ResourceManager.GetString("AuthorizeAttributeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class declared in Entities namespace not have public property &apos;{1}&apos;.
        /// </summary>
        internal static string ClassFromEntitiesPropertiesDescription {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class &apos;{0}&apos; declared in Entities namespace not have public property &apos;{1}&apos;.
        /// </summary>
        internal static string ClassFromEntitiesPropertiesMessageFormat {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPropertiesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class declared in Entities namespace shoud have public property &apos;{1}&apos;.
        /// </summary>
        internal static string ClassFromEntitiesPropertiesTitle {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class declared with xxx.Entities namespace has not modifier public.
        /// </summary>
        internal static string ClassFromEntitiesPublicDescription {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class &apos;{0}&apos; declared with xxx.Entities namespace has not modifier public.
        /// </summary>
        internal static string ClassFromEntitiesPublicMessageFormat {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPublicMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class declared in xxx.Entities namespace shuod be with modifier public.
        /// </summary>
        internal static string ClassFromEntitiesPublicTitle {
            get {
                return ResourceManager.GetString("ClassFromEntitiesPublicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class derived from System.Web.Controller has not suffix Controller.
        /// </summary>
        internal static string ControllerSuffixAnalyzerDescription {
            get {
                return ResourceManager.GetString("ControllerSuffixAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class &apos;{0}&apos; derived from System.Web.Controller has not suffix Controller.
        /// </summary>
        internal static string ControllerSuffixAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ControllerSuffixAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Classes which derived from System.Web.Controller shoud has suffix Controller.
        /// </summary>
        internal static string ControllerSuffixAnalyzerTitle {
            get {
                return ResourceManager.GetString("ControllerSuffixAnalyzerTitle", resourceCulture);
            }
        }
    }
}
